#!/bin/bash

export DISPLAY=:0.0
export XAUTHORITY=/home/chris/.Xauthority
CMD="xrandr"

declare -A VOUTS
eval VOUTS=$(xrandr | awk 'BEGIN {printf("(")} /^\S.*connected/{printf("[%s]=%s ", $1, $2)} END{printf(")")}')

declare -A POS
POS=([X]=0 [Y]=0)

find_mode() {
  echo $(xrandr | grep ${1} -A1|awk '{FS="[ x]"} /^\s/{printf("WIDTH=%s\nHEIGHT=%s", $4,$5)}')
}

xrandr_params_for() {
  if [ "${2}" == 'connected' ]
  then
    eval $(find_mode ${1})  #sets ${WIDTH} and ${HEIGHT}
    MODE="${WIDTH}x${HEIGHT}"
    CMD="${CMD} --output ${1} --mode ${MODE} --pos ${POS[X]}x${POS[Y]} --left-of LVDS1"
    POS[X]=$((${POS[X]}+${WIDTH}))
    return 0
  else
    CMD="${CMD} --output ${1} --off"
    return 1
  fi
}

for VOUT in ${!VOUTS[*]}
do
  xrandr_params_for ${VOUT} ${VOUTS[${VOUT}]}
done

#echo $CMD
${CMD}

#reset background
feh -z --bg-fill /home/chris/Pictures/Backgrounds/
