#!/bin/bash

PKGS=$(find /var/db/pkg/ -path '*-9999' -printf '%f\n')
CMD="";

for PKG in $PKGS;
do
    TIMELOC=$(find /var/db/pkg -iname $PKG)/BUILD_TIME
    TIME=$(cat $TIMELOC)
    PKGNAME=$(echo $PKG | awk 'BEGIN {OFS="-"; FS="-"} {$NF=""; print substr($0, 1, length($0)-1)}')
    cd /usr/src/$PKGNAME
    git pull -q
    GOOD=$(git log --since $TIME)
    if [[ ! -z $GOOD ]]
    then
        CMD=$CMD" "$PKGNAME
    fi
done
if [[ -z $CMD ]]
then
    echo "All packages up to date"
else
    emerge -av1 $CMD
fi
