#!/bin/bash
URL=$(hostname)

STATUS=$(curl -d '{"jsonrpc": "2.0", "id": 1, "method": "core.playback.get_state"}' http://$URL:6680/mopidy/rpc | awk '{print $6}' | cut -d '"' -f2)

if [ $STATUS = "paused" ]; then
    curl -d '{"jsonrpc": "2.0", "id": 1, "method": "core.playback.play"}' http://$URL:6680/mopidy/rpc
elif [ $STATUS = "playing" ]; then
    curl -d '{"jsonrpc": "2.0", "id": 1, "method": "core.playback.pause"}' http://$URL:6680/mopidy/rpc
fi
